/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package VistaPresentacion;

import Controlador.ControladorRegistro;
import Observer.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class DialogLogin extends javax.swing.JDialog implements Observer{
    
    private ControladorRegistro controlador;
    

   
    public DialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldNss = new javax.swing.JTextField();
        labelTxtmenu = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnVerCitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textFieldNss.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textFieldNss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNssActionPerformed(evt);
            }
        });

        labelTxtmenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTxtmenu.setText("Ingresa tu numero de seguridad social");

        btnAceptar.setBackground(new java.awt.Color(102, 102, 102));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(102, 102, 102));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al menu");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnVerCitas.setBackground(new java.awt.Color(102, 102, 102));
        btnVerCitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCitas.setText("Ver citas");
        btnVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar)
                                .addGap(15, 15, 15))
                            .addComponent(labelTxtmenu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerCitas)
                            .addComponent(textFieldNss, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTxtmenu)
                .addGap(221, 221, 221)
                .addComponent(textFieldNss, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnVolver)
                    .addComponent(btnVerCitas))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNssActionPerformed
        
       String textoNss = textFieldNss.getText().trim();
        
    }//GEN-LAST:event_textFieldNssActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        String textoNss = textFieldNss.getText().trim();
        
         if (textoNss.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número.");
            return;
        }

        try {
            // 3. Convierte el texto a número.
            int nss = Integer.parseInt(textoNss);

            controlador.validarPacienteYMostrarMenu(nss, this);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número válido.");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
        controlador.iniciar();
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCitasActionPerformed
        
        String textoNss = textFieldNss.getText().trim();
        
         if (textoNss.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número.");
            return;
        }

        
            // 3. Convierte el texto a número.
            int nss = Integer.parseInt(textoNss);
        controlador.buscarPacienteYMostrarCitas( nss, this);
       
        
        
    }//GEN-LAST:event_btnVerCitasActionPerformed

    // metodos
    
     public void setControlador (ControladorRegistro controlador ) {
        this.controlador = controlador;
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVerCitas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel labelTxtmenu;
    private javax.swing.JTextField textFieldNss;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
       
    }
}
